### ISSUE TITLE
很不错的一个模块，如果是安装在一个单片机板子里，不能点确定，如何更新呢？

### ISSUE THREAD

**Issue by huge818** [vaenow/cordova-plugin-app-update-demo#2]
很不错的一个模块，

如果是安装在一个单片机板子里，没有屏幕点确定，如何更新呢？

真实的需求是静默下载，自动升级，能做到吗？

我也写了一个插件，安卓上的tcp-server 欢迎交流
https://github.com/huge818/socketServer
QQ464055812

**Comment by vaenow** [comment]
可以把代码Fork下来，把“确认更新”那里的代码改为自动更新就好。

如果可能，希望你能把这个插件改为`可配置的自动更新`，然后提交**Pull Request**，帮助它为更多的用户服务

**Comment by vaenow** [comment]
这是之前相同的问题：

[Update without confirm：https://github.com/vaenow/cordova-plugin-app-update/issues/25](https://github.com/vaenow/cordova-plugin-app-update/issues/25)

**Comment by huge818** [comment]
谢谢，我已经fork了




------------------ 原始邮件 ------------------
发件人: "Wen Luo";<notifications@github.com>;
发送时间: 2017年9月26日(星期二) 下午4:44
收件人: "vaenow/cordova-plugin-app-update-demo"<cordova-plugin-app-update-demo@noreply.github.com>;
抄送: "传说中的湖"<huzc818@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [vaenow/cordova-plugin-app-update-demo] 很不错的一个模块，如果是安装在一个单片机板子里，不能点确定，如何更新呢？ (#2)




这是之前相同的问题：
 
Update without confirm：https://github.com/vaenow/cordova-plugin-app-update/issues/25
